feat: [TKC-4043] selenium - example projects and workflows (java, python, js+mocha, js+cucumber) (#6634)
* example selenium-java project

* example selenium-java project - tests updated

* example selenium-java project - tests updated

* example selenium-java project - tests updated

* example selenium-java project - tests updated

* java test updated

* selenium python project added

* selenium java project updated

* selenium python project updated

* selenium python project updated - pytest -q flag disabled

* selenium python project updated - sleep

* selenium python project updated - sleep

* selenium workflows updated

* special cases - service name with dash

* selenium-js-cucumber, selenium-js-mocha

* selenium-js-mocha - type

* selenium-js-mocha - mocha multi-reporters

* selenium-js-cucumber - project fixed

* selenium-js-cucumber - project updated

* cucumber config fixed

* cucumber dir structure fixed

* selenium workflows - branches updated

* workflow suites updated

* workflow suites updated

diff --git a/test/special-cases/special-cases-additional.yaml b/test/special-cases/special-cases-additional.yaml
--- a/test/special-cases/special-cases-additional.yaml
+++ b/test/special-cases/special-cases-additional.yaml
@@ -14,3 +14,32 @@ spec:
         echo "Iteration $iteration, sleep (1 second)"
         sleep 1
       done
+---
+apiVersion: testworkflows.testkube.io/v1
+kind: TestWorkflow
+metadata:
+  name: special-cases-service-name-with-dash  # only . notation is supported (https://linear.app/kubeshop/issue/TKC-4047/)
+  labels:
+    core-tests: special-cases
+description: "Service name with dash"
+spec:
+  container:
+    image: alpine:3.22.0
+  services:
+    service-name-with-dash:
+      image: alpine:3.22.0
+      logs: always
+      count: 1
+      shell: 'echo "started service" && sleep 60'
+  job:
+    activeDeadlineSeconds: 30
+  steps:
+  - name: Step
+    run:
+      shell: |
+        echo "Service IP: {{ at(services, "service-name-with-dash").0.ip }}"
+        echo "Service ENV: $SERVICE_IP"
+        [ -z "$SERVICE_IP" ] && { echo "ERROR: SERVICE_IP empty"; exit 1; } || echo OK
+      env:
+        - name: SERVICE_IP
+          value: '{{ at(services, "service-name-with-dash").0.ip }}'
